#!/usr/bin/env bash
# a script to test your luck for today!!

i=0
while [ $i -lt 20 ]
do
	((i++))
        case "$i" in
		4)
			echo "4"
			echo "bad luck from China"
			;;
		9)
			echo "9"
			echo "bad luck from Japan"
			;;
		17)
			echo "17"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
	esac
done
